{
 "title": "Adapter metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ReadySet query latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ReadySet QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(readyset_query_log_execution_time_count{database_type=\"readyset\"}[$__rate_interval])",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "Query execution (readyset) - p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "readyset_query_log_execution_time{quantile=\"0.5\", database_type=\"readyset\"}",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "Query execution (readyset) - p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "readyset_query_log_execution_time{quantile=\"0.99\", database_type=\"readyset\"}",
       "legendFormat": "{{query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Proxied query latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proxied QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(readyset_query_log_execution_time_count{database_type!=\"readyset\"}[$__rate_interval])",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "Query execution (upstream) - p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "readyset_query_log_execution_time{quantile=\"0.5\", database_type!=\"readyset\"}",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "Query execution (upstream) - p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "readyset_query_log_execution_time{quantile=\"0.99\", database_type!=\"readyset\"}",
       "legendFormat": "{{query}}"
      }
     ]
    }
   ]
  },
  { "title": "Query parsing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Parse failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(readyset_query_log_parse_errors[$__rate_interval])",
     "legendFormat": "parse fail count"
    }
   ]
  },
  {
   "title": "SET disallowed count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "delta(readyset_query_log_set_disallowed[$__interval])",
     "legendFormat": "SET disallowed count"
    }
   ]
  },
  {
   "title": "Query parse time - p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "readyset_query_log_parse_time{quantile=\"0.5\"}",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Query parse time - p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "readyset_query_log_parse_time{quantile=\"0.99\"}",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "readyset_noria_client_connected_clients",
       "legendFormat": "client count"
      },
      {
       "expr": "readyset_client_upstream_connections",
       "legendFormat": "upstream connections"
      }
     ]
    },
    {
     "title": "ViewNotFound counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "rate(readyset_query_log_view_not_found[$__rate_interval])",
       "legendFormat": "ViewNotFound count"
      }
     ]
    }
   ]
  },
  { "title": "ReadySet misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "ReadySet cache misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(readyset_query_log_total_cache_misses[$__rate_interval])",
     "legendFormat": "cache keys miss::{{query}}"
    },
    {
     "expr": "readyset_query_log_query_cache_missed",
     "legendFormat": "cache miss::{{query}}"
    }
   ]
  },
  {
   "title": "Keys read per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(readyset_query_log_total_keys_read[$__rate_interval])",
     "legendFormat": "{{query}}"
    }
   ]
  }
 ]
}