{
 "title": "ReadySet perf",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Query parsing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Parse failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(readyset_query_log_parse_errors[$__rate_interval])",
     "legendFormat": "parse fail count"
    }
   ]
  },
  {
   "title": "ViewNotFound counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(readyset_query_log_view_not_found[$__rate_interval])",
     "legendFormat": "ViewNotFound count"
    }
   ]
  },
  {
   "title": "Query parse time - p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "readyset_query_log_parse_time{quantile=\"0.5\"}",
     "legendFormat": "parse time "
    }
   ]
  },
  {
   "title": "Query parse time - p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "readyset_query_log_parse_time{quantile=\"0.99\"}",
     "legendFormat": "parse time "
    }
   ]
  },
  { "title": "Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Connected clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "readyset_noria_client_connected_clients",
     "legendFormat": "client count"
    }
   ]
  }
 ]
}