[target.x86_64-unknown-linux-gnu]
# Use mold linker with no-rosegment flag for better flamegraphs
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "link-arg=-Wl,--no-rosegment"]

[alias]
nt = "nextest run --workspace --features failure_injection --exclude readyset-clustertest --no-fail-fast"
