version: "3.8"
services:
  ##############################
  ## databases
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=readyset
      - MYSQL_DATABASE=testdb
    ports:
     - '3306:3306'
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=readyset
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"


  ##############################
  ## additional high-level services
  consul-server:
    image: hashicorp/consul:1.15
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    restart: always
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
    command: 'agent -bootstrap-expect=1'

  
  ##############################
  ## metrics, metrics everywhere
  prometheus:
    image: prom/prometheus
    network_mode: "host"
    volumes:
      - ./prometheus/prometheus-laptop.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/var/lib/prometheus
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9090"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 5s
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    network_mode: "host"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config:/etc/grafana

  ##############################
  ## metrics exporters
  postgres_exporter:
    # https://github.com/prometheus-community/postgres_exporter
    # defaults to port 9187
    image: prometheuscommunity/postgres-exporter
    network_mode: "host"
    environment:
      - DATA_SOURCE_URI=0.0.0.0:5432?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=readyset

  pushgateway:
    # allows ephemeral and batch jobs to expose their metrics to Prometheus
    # https://github.com/prometheus/pushgateway
    # defaults to port 9091
    image: prom/pushgateway
    network_mode: "host"

  node_exporter:
    # exporter for hardware and OS metrics exposed by *NIX kernels
    # https://github.com/prometheus/node_exporter
    # https://prometheus.io/docs/guides/node-exporter/
    # default port of 9100
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'


##############################
## volumes for specific apps
volumes:
  prometheus-data: {}
